# Generated by Django 4.0.5 on 2022-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('password1', models.IntegerField()),
                ('password2', models.IntegerField()),
            ],
        ),
    ]
