# Generated by Django 4.0.5 on 2022-06-24 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('c_slug', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=150, unique=True)),
                ('p_slug', models.CharField(max_length=150, unique=True)),
                ('p_desc', models.TextField()),
                ('p_img', models.ImageField(upload_to='products_img')),
                ('p_price', models.IntegerField()),
                ('p_stock', models.IntegerField()),
                ('p_available', models.BooleanField()),
                ('p_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.category')),
            ],
        ),
    ]
