# Generated by Django 4.0.5 on 2022-06-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_rename_name_category_c_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
